<a href="https://colab.research.google.com/github/bastow-libby/379-Final-Project/blob/main/Final_Project_379.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [185]:
import pandas as pd
import sqlite3
import glob
from datetime import datetime

# Suppress warnings generated by your code:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')

Extraction

In [186]:
# Stages of the ETL process are logged into this file
log_file = 'etl_log_file.txt'

# The names of the sqlite database and table to created to store the cleaned data
db_name = 'hr.db'
table_name = 'employees'

Examine the contents of the different types of files to see the formatting for extraction

In [187]:
# load one csv to discover its content, columns, etc.
df = pd.read_csv('ids_0.csv')

# display the data types of the columns
print(df.dtypes)

# display the head of the dataframe
df.head()

# print the columns
print(df.columns)

 Destination Port                 int64
 Flow Duration                    int64
 Total Fwd Packets                int64
 Total Backward Packets           int64
Total Length of Fwd Packets       int64
 Total Length of Bwd Packets      int64
 Fwd Packet Length Max            int64
 Fwd Packet Length Min            int64
 Fwd Packet Length Mean         float64
 Fwd Packet Length Std          float64
Bwd Packet Length Max             int64
 Bwd Packet Length Min            int64
 Bwd Packet Length Mean         float64
 Bwd Packet Length Std          float64
Flow Bytes/s                    float64
 Flow Packets/s                 float64
 Flow IAT Mean                  float64
 Flow IAT Std                   float64
 Flow IAT Max                     int64
 Flow IAT Min                     int64
Fwd IAT Total                     int64
 Fwd IAT Mean                   float64
 Fwd IAT Std                    float64
 Fwd IAT Max                      int64
 Fwd IAT Min                      int64
Bwd IAT Total                     int64
 Bwd IAT Mean                   float64
 Bwd IAT Std                    float64
 Bwd IAT Max                      int64
 Bwd IAT Min                      int64
Fwd PSH Flags                     int64
 Bwd PSH Flags                    int64
 Fwd URG Flags                    int64
 Bwd URG Flags                    int64
 Fwd Header Length                int64
 Bwd Header Length                int64
Fwd Packets/s                   float64
 Bwd Packets/s                  float64
 Min Packet Length                int64
 Max Packet Length                int64
 Packet Length Mean             float64
 Packet Length Std              float64
 Packet Length Variance         float64
FIN Flag Count                    int64
 SYN Flag Count                   int64
 RST Flag Count                   int64
 PSH Flag Count                   int64
 ACK Flag Count                   int64
 URG Flag Count                   int64
 CWE Flag Count                   int64
 ECE Flag Count                   int64
 Down/Up Ratio                    int64
 Average Packet Size            float64
 Avg Fwd Segment Size           float64
 Avg Bwd Segment Size           float64
 Fwd Header Length.1              int64
Fwd Avg Bytes/Bulk                int64
 Fwd Avg Packets/Bulk             int64
 Fwd Avg Bulk Rate                int64
 Bwd Avg Bytes/Bulk               int64
 Bwd Avg Packets/Bulk             int64
Bwd Avg Bulk Rate                 int64
Subflow Fwd Packets               int64
 Subflow Fwd Bytes                int64
 Subflow Bwd Packets              int64
 Subflow Bwd Bytes                int64
Init_Win_bytes_forward            int64
 Init_Win_bytes_backward          int64
 act_data_pkt_fwd                 int64
 min_seg_size_forward             int64
Active Mean                     float64
 Active Std                     float64
 Active Max                       int64
 Active Min                       int64
Idle Mean                       float64
 Idle Std                       float64
 Idle Max                         int64
 Idle Min                         int64
 Label                           object
dtype: object
Index([' Destination Port', ' Flow Duration', ' Total Fwd Packets',
       ' Total Backward Packets', 'Total Length of Fwd Packets',
       ' Total Length of Bwd Packets', ' Fwd Packet Length Max',
       ' Fwd Packet Length Min', ' Fwd Packet Length Mean',
       ' Fwd Packet Length Std', 'Bwd Packet Length Max',
       ' Bwd Packet Length Min', ' Bwd Packet Length Mean',
       ' Bwd Packet Length Std', 'Flow Bytes/s', ' Flow Packets/s',
       ' Flow IAT Mean', ' Flow IAT Std', ' Flow IAT Max', ' Flow IAT Min',
       'Fwd IAT Total', ' Fwd IAT Mean', ' Fwd IAT Std', ' Fwd IAT Max',
       ' Fwd IAT Min', 'Bwd IAT Total', ' Bwd IAT Mean', ' Bwd IAT Std',
       ' Bwd IAT Max', ' Bwd IAT Min', 'Fwd PSH Flags', ' Bwd PSH Flags',
       ' Fwd URG Flags', ' Bwd URG Flags', ' Fwd Header Length',
       ' Bwd Header Length', 'Fwd Packets/s', ' Bwd Packets/s',
       ' Min Packet Length', ' Max Packet Length', ' Packet Length Mean',
       ' Packet Length Std', ' Packet Length Variance', 'FIN Flag Count',
       ' SYN Flag Count', ' RST Flag Count', ' PSH Flag Count',
       ' ACK Flag Count', ' URG Flag Count', ' CWE Flag Count',
       ' ECE Flag Count', ' Down/Up Ratio', ' Average Packet Size',
       ' Avg Fwd Segment Size', ' Avg Bwd Segment Size',
       ' Fwd Header Length.1', 'Fwd Avg Bytes/Bulk', ' Fwd Avg Packets/Bulk',
       ' Fwd Avg Bulk Rate', ' Bwd Avg Bytes/Bulk', ' Bwd Avg Packets/Bulk',
       'Bwd Avg Bulk Rate', 'Subflow Fwd Packets', ' Subflow Fwd Bytes',
       ' Subflow Bwd Packets', ' Subflow Bwd Bytes', 'Init_Win_bytes_forward',
       ' Init_Win_bytes_backward', ' act_data_pkt_fwd',
       ' min_seg_size_forward', 'Active Mean', ' Active Std', ' Active Max',
       ' Active Min', 'Idle Mean', ' Idle Std', ' Idle Max', ' Idle Min',
       ' Label'],
      dtype='object')

In [188]:
# load one json to discover its content, columns, etc.
df = pd.read_json('ids_4.json', lines=True)

# display the data types of the columns
print(df.dtypes)

# display the head of the dataframe
df.head()

 Destination Port                 int64
 Flow Duration                    int64
 Total Fwd Packets                int64
 Total Backward Packets           int64
Total Length of Fwd Packets       int64
 Total Length of Bwd Packets      int64
 Fwd Packet Length Max            int64
 Fwd Packet Length Min            int64
 Fwd Packet Length Mean         float64
 Fwd Packet Length Std          float64
Bwd Packet Length Max             int64
 Bwd Packet Length Min            int64
 Bwd Packet Length Mean         float64
 Bwd Packet Length Std          float64
Flow Bytes/s                    float64
 Flow Packets/s                 float64
 Flow IAT Mean                  float64
 Flow IAT Std                   float64
 Flow IAT Max                     int64
 Flow IAT Min                     int64
Fwd IAT Total                     int64
 Fwd IAT Mean                   float64
 Fwd IAT Std                    float64
 Fwd IAT Max                      int64
 Fwd IAT Min                      int64
Bwd IAT Total                     int64
 Bwd IAT Mean                   float64
 Bwd IAT Std                    float64
 Bwd IAT Max                      int64
 Bwd IAT Min                      int64
Fwd PSH Flags                     int64
 Bwd PSH Flags                    int64
 Fwd URG Flags                    int64
 Bwd URG Flags                    int64
 Fwd Header Length                int64
 Bwd Header Length                int64
Fwd Packets/s                   float64
 Bwd Packets/s                  float64
 Min Packet Length                int64
 Max Packet Length                int64
 Packet Length Mean             float64
 Packet Length Std              float64
 Packet Length Variance         float64
FIN Flag Count                    int64
 SYN Flag Count                   int64
 RST Flag Count                   int64
 PSH Flag Count                   int64
 ACK Flag Count                   int64
 URG Flag Count                   int64
 CWE Flag Count                   int64
 ECE Flag Count                   int64
 Down/Up Ratio                    int64
 Average Packet Size            float64
 Avg Fwd Segment Size           float64
 Avg Bwd Segment Size           float64
 Fwd Header Length.1              int64
Fwd Avg Bytes/Bulk                int64
 Fwd Avg Packets/Bulk             int64
 Fwd Avg Bulk Rate                int64
 Bwd Avg Bytes/Bulk               int64
 Bwd Avg Packets/Bulk             int64
Bwd Avg Bulk Rate                 int64
Subflow Fwd Packets               int64
 Subflow Fwd Bytes                int64
 Subflow Bwd Packets              int64
 Subflow Bwd Bytes                int64
Init_Win_bytes_forward            int64
 Init_Win_bytes_backward          int64
 act_data_pkt_fwd                 int64
 min_seg_size_forward             int64
Active Mean                     float64
 Active Std                     float64
 Active Max                       int64
 Active Min                       int64
Idle Mean                       float64
 Idle Std                       float64
 Idle Max                         int64
 Idle Min                         int64
 Label                           object
dtype: object

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,80,27887,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
1,53,181,2,2,74,154,37,37,37.0,0.0,...,44,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2,80,115,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
3,80,13,1,1,6,6,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
4,56529,50,1,1,0,0,0,0,0.0,0.0,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN

In [189]:
# load one parquet to discover its content, columns, etc.
df = pd.read_parquet('ids_5.parquet')

# display the data types of the columns
print(df.dtypes)

# display the head of the dataframe
df.head()

 Destination Port                 int64
 Flow Duration                    int64
 Total Fwd Packets                int64
 Total Backward Packets           int64
Total Length of Fwd Packets       int64
 Total Length of Bwd Packets      int64
 Fwd Packet Length Max            int64
 Fwd Packet Length Min            int64
 Fwd Packet Length Mean         float64
 Fwd Packet Length Std          float64
Bwd Packet Length Max             int64
 Bwd Packet Length Min            int64
 Bwd Packet Length Mean         float64
 Bwd Packet Length Std          float64
Flow Bytes/s                    float64
 Flow Packets/s                 float64
 Flow IAT Mean                  float64
 Flow IAT Std                   float64
 Flow IAT Max                     int64
 Flow IAT Min                     int64
Fwd IAT Total                     int64
 Fwd IAT Mean                   float64
 Fwd IAT Std                    float64
 Fwd IAT Max                      int64
 Fwd IAT Min                      int64
Bwd IAT Total                     int64
 Bwd IAT Mean                   float64
 Bwd IAT Std                    float64
 Bwd IAT Max                      int64
 Bwd IAT Min                      int64
Fwd PSH Flags                     int64
 Bwd PSH Flags                    int64
 Fwd URG Flags                    int64
 Bwd URG Flags                    int64
 Fwd Header Length                int64
 Bwd Header Length                int64
Fwd Packets/s                   float64
 Bwd Packets/s                  float64
 Min Packet Length                int64
 Max Packet Length                int64
 Packet Length Mean             float64
 Packet Length Std              float64
 Packet Length Variance         float64
FIN Flag Count                    int64
 SYN Flag Count                   int64
 RST Flag Count                   int64
 PSH Flag Count                   int64
 ACK Flag Count                   int64
 URG Flag Count                   int64
 CWE Flag Count                   int64
 ECE Flag Count                   int64
 Down/Up Ratio                    int64
 Average Packet Size            float64
 Avg Fwd Segment Size           float64
 Avg Bwd Segment Size           float64
 Fwd Header Length.1              int64
Fwd Avg Bytes/Bulk                int64
 Fwd Avg Packets/Bulk             int64
 Fwd Avg Bulk Rate                int64
 Bwd Avg Bytes/Bulk               int64
 Bwd Avg Packets/Bulk             int64
Bwd Avg Bulk Rate                 int64
Subflow Fwd Packets               int64
 Subflow Fwd Bytes                int64
 Subflow Bwd Packets              int64
 Subflow Bwd Bytes                int64
Init_Win_bytes_forward            int64
 Init_Win_bytes_backward          int64
 act_data_pkt_fwd                 int64
 min_seg_size_forward             int64
Active Mean                     float64
 Active Std                     float64
 Active Max                       int64
 Active Min                       int64
Idle Mean                       float64
 Idle Std                       float64
 Idle Max                         int64
 Idle Min                         int64
 Label                           object
dtype: object

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,80,14258,2,2,12,0,6,6,6.000000,0.000000,...,20,0.0,0.0,0,0,0.0,0.0,0,0,DoS Hulk
1,80,116312384,6,6,423,11595,411,0,70.500000,166.836147,...,20,6999.0,0.0,6999,6999,58200000.0,59600000.0,100000000,16000000,DoS Hulk
2,80,3,2,0,0,0,0,0,0.000000,0.000000,...,32,0.0,0.0,0,0,0.0,0.0,0,0,DoS Hulk
3,80,84082357,9,7,366,11595,366,0,40.666667,122.000000,...,32,995.0,0.0,995,995,83900000.0,0.0,83900000,83900000,DoS Hulk
4,80,2,2,0,0,0,0,0,0.000000,0.000000,...,32,0.0,0.0,0,0,0.0,0.0,0,0,DoS Hulk

Since the columns appear to be the same, we will extract the data and then clean it

In [190]:
def extract() -> pd.DataFrame:
    """This function combines all the csv and json files into a dataframe

    Args:
        None: The function reads all csv and json files in the working directory

    Returns:
        data (pd.DataFrame): All data sources combined in a single dataframe
    """
    ## create an empty dataframe to hold all the data
    # The columns' names are given based on an earlier exploration of a csv file
    data = pd.DataFrame(columns=[' Destination Port', ' Flow Duration', ' Total Fwd Packets',
       ' Total Backward Packets', 'Total Length of Fwd Packets',
       ' Total Length of Bwd Packets', ' Fwd Packet Length Max',
       ' Fwd Packet Length Min', ' Fwd Packet Length Mean',
       ' Fwd Packet Length Std', 'Bwd Packet Length Max',
       ' Bwd Packet Length Min', ' Bwd Packet Length Mean',
       ' Bwd Packet Length Std', 'Flow Bytes/s', ' Flow Packets/s',
       ' Flow IAT Mean', ' Flow IAT Std', ' Flow IAT Max', ' Flow IAT Min',
       'Fwd IAT Total', ' Fwd IAT Mean', ' Fwd IAT Std', ' Fwd IAT Max',
       ' Fwd IAT Min', 'Bwd IAT Total', ' Bwd IAT Mean', ' Bwd IAT Std',
       ' Bwd IAT Max', ' Bwd IAT Min', 'Fwd PSH Flags', ' Bwd PSH Flags',
       ' Fwd URG Flags', ' Bwd URG Flags', ' Fwd Header Length',
       ' Bwd Header Length', 'Fwd Packets/s', ' Bwd Packets/s',
       ' Min Packet Length', ' Max Packet Length', ' Packet Length Mean',
       ' Packet Length Std', ' Packet Length Variance', 'FIN Flag Count',
       ' SYN Flag Count', ' RST Flag Count', ' PSH Flag Count',
       ' ACK Flag Count', ' URG Flag Count', ' CWE Flag Count',
       ' ECE Flag Count', ' Down/Up Ratio', ' Average Packet Size',
       ' Avg Fwd Segment Size', ' Avg Bwd Segment Size',
       ' Fwd Header Length.1', 'Fwd Avg Bytes/Bulk', ' Fwd Avg Packets/Bulk',
       ' Fwd Avg Bulk Rate', ' Bwd Avg Bytes/Bulk', ' Bwd Avg Packets/Bulk',
       'Bwd Avg Bulk Rate', 'Subflow Fwd Packets', ' Subflow Fwd Bytes',
       ' Subflow Bwd Packets', ' Subflow Bwd Bytes', 'Init_Win_bytes_forward',
       ' Init_Win_bytes_backward', ' act_data_pkt_fwd',
       ' min_seg_size_forward', 'Active Mean', ' Active Std', ' Active Max',
       ' Active Min', 'Idle Mean', ' Idle Std', ' Idle Max', ' Idle Min',
       ' Label'])

    ## glob.glob('*.csv')
    #
    for csvfile in glob.glob('*.csv'):
        # load the current csv file into a temporary dataframe
        tmp_df = pd.read_csv(csvfile)

        # concatenate the loaded data with the data frame
        data = pd.concat([data, tmp_df], ignore_index=True)

    ## glob.glob('*.json')

    for jsonfile in glob.glob('*.json'):
        # load the current json file into a temporary dataframe
        tmp_df = pd.read_json(jsonfile, lines=True)

        # concatenate the loaded data to the data frame
        data = pd.concat([data, tmp_df], ignore_index=True)

    ## glob.glob ('*parquet')
    for parquetfile in glob.glob('*.parquet'):
        # load the current parquet file into a temporary dataframe
        tmp_df = pd.read_parquet(parquetfile)

        # concatenate the loaded data to the data frame
        data = pd.concat([data, tmp_df], ignore_index=True)

    # return the combined (extracted) data
    return data

In [191]:
data = extract()
print(data.dtypes)
print('data shape:', data.shape)
print('column names:', data.columns)

 Destination Port                object
 Flow Duration                   object
 Total Fwd Packets               object
 Total Backward Packets          object
Total Length of Fwd Packets      object
 Total Length of Bwd Packets     object
 Fwd Packet Length Max           object
 Fwd Packet Length Min           object
 Fwd Packet Length Mean         float64
 Fwd Packet Length Std          float64
Bwd Packet Length Max            object
 Bwd Packet Length Min           object
 Bwd Packet Length Mean         float64
 Bwd Packet Length Std          float64
Flow Bytes/s                    float64
 Flow Packets/s                 float64
 Flow IAT Mean                  float64
 Flow IAT Std                   float64
 Flow IAT Max                    object
 Flow IAT Min                    object
Fwd IAT Total                    object
 Fwd IAT Mean                   float64
 Fwd IAT Std                    float64
 Fwd IAT Max                     object
 Fwd IAT Min                     object
Bwd IAT Total                    object
 Bwd IAT Mean                   float64
 Bwd IAT Std                    float64
 Bwd IAT Max                     object
 Bwd IAT Min                     object
Fwd PSH Flags                    object
 Bwd PSH Flags                   object
 Fwd URG Flags                   object
 Bwd URG Flags                   object
 Fwd Header Length               object
 Bwd Header Length               object
Fwd Packets/s                   float64
 Bwd Packets/s                  float64
 Min Packet Length               object
 Max Packet Length               object
 Packet Length Mean             float64
 Packet Length Std              float64
 Packet Length Variance         float64
FIN Flag Count                   object
 SYN Flag Count                  object
 RST Flag Count                  object
 PSH Flag Count                  object
 ACK Flag Count                  object
 URG Flag Count                  object
 CWE Flag Count                  object
 ECE Flag Count                  object
 Down/Up Ratio                   object
 Average Packet Size            float64
 Avg Fwd Segment Size           float64
 Avg Bwd Segment Size           float64
 Fwd Header Length.1             object
Fwd Avg Bytes/Bulk               object
 Fwd Avg Packets/Bulk            object
 Fwd Avg Bulk Rate               object
 Bwd Avg Bytes/Bulk              object
 Bwd Avg Packets/Bulk            object
Bwd Avg Bulk Rate                object
Subflow Fwd Packets              object
 Subflow Fwd Bytes               object
 Subflow Bwd Packets             object
 Subflow Bwd Bytes               object
Init_Win_bytes_forward           object
 Init_Win_bytes_backward         object
 act_data_pkt_fwd                object
 min_seg_size_forward            object
Active Mean                     float64
 Active Std                     float64
 Active Max                      object
 Active Min                      object
Idle Mean                       float64
 Idle Std                       float64
 Idle Max                        object
 Idle Min                        object
 Label                           object
dtype: object
data shape: (63129, 79)
column names: Index([' Destination Port', ' Flow Duration', ' Total Fwd Packets',
       ' Total Backward Packets', 'Total Length of Fwd Packets',
       ' Total Length of Bwd Packets', ' Fwd Packet Length Max',
       ' Fwd Packet Length Min', ' Fwd Packet Length Mean',
       ' Fwd Packet Length Std', 'Bwd Packet Length Max',
       ' Bwd Packet Length Min', ' Bwd Packet Length Mean',
       ' Bwd Packet Length Std', 'Flow Bytes/s', ' Flow Packets/s',
       ' Flow IAT Mean', ' Flow IAT Std', ' Flow IAT Max', ' Flow IAT Min',
       'Fwd IAT Total', ' Fwd IAT Mean', ' Fwd IAT Std', ' Fwd IAT Max',
       ' Fwd IAT Min', 'Bwd IAT Total', ' Bwd IAT Mean', ' Bwd IAT Std',
       ' Bwd IAT Max', ' Bwd IAT Min', 'Fwd PSH Flags', ' Bwd PSH Flags',
       ' Fwd URG Flags', ' Bwd URG Flags', ' Fwd Header Length',
       ' Bwd Header Length', 'Fwd Packets/s', ' Bwd Packets/s',
       ' Min Packet Length', ' Max Packet Length', ' Packet Length Mean',
       ' Packet Length Std', ' Packet Length Variance', 'FIN Flag Count',
       ' SYN Flag Count', ' RST Flag Count', ' PSH Flag Count',
       ' ACK Flag Count', ' URG Flag Count', ' CWE Flag Count',
       ' ECE Flag Count', ' Down/Up Ratio', ' Average Packet Size',
       ' Avg Fwd Segment Size', ' Avg Bwd Segment Size',
       ' Fwd Header Length.1', 'Fwd Avg Bytes/Bulk', ' Fwd Avg Packets/Bulk',
       ' Fwd Avg Bulk Rate', ' Bwd Avg Bytes/Bulk', ' Bwd Avg Packets/Bulk',
       'Bwd Avg Bulk Rate', 'Subflow Fwd Packets', ' Subflow Fwd Bytes',
       ' Subflow Bwd Packets', ' Subflow Bwd Bytes', 'Init_Win_bytes_forward',
       ' Init_Win_bytes_backward', ' act_data_pkt_fwd',
       ' min_seg_size_forward', 'Active Mean', ' Active Std', ' Active Max',
       ' Active Min', 'Idle Mean', ' Idle Std', ' Idle Max', ' Idle Min',
       ' Label'],
      dtype='object')

Transform Stage

First, we will identify any NaNs

In [192]:
from math import nan
import math
#Adjust the display function to see all columns
pd.options.display.max_rows = 500

print(data.isna().sum())

print(f'Total number of missing values: {data.isna().sum().sum()}')

 Destination Port                 0
 Flow Duration                    0
 Total Fwd Packets                0
 Total Backward Packets           0
Total Length of Fwd Packets       0
 Total Length of Bwd Packets      0
 Fwd Packet Length Max            0
 Fwd Packet Length Min            0
 Fwd Packet Length Mean           0
 Fwd Packet Length Std            0
Bwd Packet Length Max             0
 Bwd Packet Length Min            0
 Bwd Packet Length Mean           0
 Bwd Packet Length Std            0
Flow Bytes/s                    118
 Flow Packets/s                  33
 Flow IAT Mean                    0
 Flow IAT Std                     0
 Flow IAT Max                     0
 Flow IAT Min                     0
Fwd IAT Total                     0
 Fwd IAT Mean                     0
 Fwd IAT Std                      0
 Fwd IAT Max                      0
 Fwd IAT Min                      0
Bwd IAT Total                     0
 Bwd IAT Mean                     0
 Bwd IAT Std                      0
 Bwd IAT Max                      0
 Bwd IAT Min                      0
Fwd PSH Flags                     0
 Bwd PSH Flags                    0
 Fwd URG Flags                    0
 Bwd URG Flags                    0
 Fwd Header Length                0
 Bwd Header Length                0
Fwd Packets/s                     0
 Bwd Packets/s                    0
 Min Packet Length                0
 Max Packet Length                0
 Packet Length Mean               0
 Packet Length Std                0
 Packet Length Variance           0
FIN Flag Count                    0
 SYN Flag Count                   0
 RST Flag Count                   0
 PSH Flag Count                   0
 ACK Flag Count                   0
 URG Flag Count                   0
 CWE Flag Count                   0
 ECE Flag Count                   0
 Down/Up Ratio                    0
 Average Packet Size              0
 Avg Fwd Segment Size             0
 Avg Bwd Segment Size             0
 Fwd Header Length.1              0
Fwd Avg Bytes/Bulk                0
 Fwd Avg Packets/Bulk             0
 Fwd Avg Bulk Rate                0
 Bwd Avg Bytes/Bulk               0
 Bwd Avg Packets/Bulk             0
Bwd Avg Bulk Rate                 0
Subflow Fwd Packets               0
 Subflow Fwd Bytes                0
 Subflow Bwd Packets              0
 Subflow Bwd Bytes                0
Init_Win_bytes_forward            0
 Init_Win_bytes_backward          0
 act_data_pkt_fwd                 0
 min_seg_size_forward             0
Active Mean                       0
 Active Std                       0
 Active Max                       0
 Active Min                       0
Idle Mean                         0
 Idle Std                         0
 Idle Max                         0
 Idle Min                         0
 Label                            0
dtype: int64
Total number of missing values: 151

Since there are so few missing values, and we are trying to identify each packet, we will drop the rows with missing values rather than fill them in with averages.

In [193]:
data.dropna(inplace=True)

print(f'Total number of missing values: {data.isna().sum().sum()}')

Total number of missing values: 0

Now, we need to drop all heartbleed instances, as they are not DoS attacks

In [194]:
data = data[data[' Label'] != 'Heartbleed']
print('data shape:', data.shape)

data shape: (63000, 79)

Next, we need to adjust the labels for all DoS attacks so they can be boolean (grouped together under attack rather than by label)

In [195]:

data[' Label'] = data[' Label'].where(data[' Label'] == 'BENIGN', 'ATTACK')

We need to convert the values to integers now

In [196]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 63000 entries, 0 to 63128
Data columns (total 79 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0    Destination Port             63000 non-null  object
 1    Flow Duration                63000 non-null  object
 2    Total Fwd Packets            63000 non-null  object
 3    Total Backward Packets       63000 non-null  object
 4   Total Length of Fwd Packets   63000 non-null  object
 5    Total Length of Bwd Packets  63000 non-null  object
 6    Fwd Packet Length Max        63000 non-null  object
 7    Fwd Packet Length Min        63000 non-null  object
 8    Fwd Packet Length Mean       63000 non-null  float64
 9    Fwd Packet Length Std        63000 non-null  float64
 10  Bwd Packet Length Max         63000 non-null  object
 11   Bwd Packet Length Min        63000 non-null  object
 12   Bwd Packet Length Mean       63000 non-null  float64
 13   Bwd Packet Length Std        63000 non-null  float64
 14  Flow Bytes/s                  63000 non-null  float64
 15   Flow Packets/s               63000 non-null  float64
 16   Flow IAT Mean                63000 non-null  float64
 17   Flow IAT Std                 63000 non-null  float64
 18   Flow IAT Max                 63000 non-null  object
 19   Flow IAT Min                 63000 non-null  object
 20  Fwd IAT Total                 63000 non-null  object
 21   Fwd IAT Mean                 63000 non-null  float64
 22   Fwd IAT Std                  63000 non-null  float64
 23   Fwd IAT Max                  63000 non-null  object
 24   Fwd IAT Min                  63000 non-null  object
 25  Bwd IAT Total                 63000 non-null  object
 26   Bwd IAT Mean                 63000 non-null  float64
 27   Bwd IAT Std                  63000 non-null  float64
 28   Bwd IAT Max                  63000 non-null  object
 29   Bwd IAT Min                  63000 non-null  object
 30  Fwd PSH Flags                 63000 non-null  object
 31   Bwd PSH Flags                63000 non-null  object
 32   Fwd URG Flags                63000 non-null  object
 33   Bwd URG Flags                63000 non-null  object
 34   Fwd Header Length            63000 non-null  object
 35   Bwd Header Length            63000 non-null  object
 36  Fwd Packets/s                 63000 non-null  float64
 37   Bwd Packets/s                63000 non-null  float64
 38   Min Packet Length            63000 non-null  object
 39   Max Packet Length            63000 non-null  object
 40   Packet Length Mean           63000 non-null  float64
 41   Packet Length Std            63000 non-null  float64
 42   Packet Length Variance       63000 non-null  float64
 43  FIN Flag Count                63000 non-null  object
 44   SYN Flag Count               63000 non-null  object
 45   RST Flag Count               63000 non-null  object
 46   PSH Flag Count               63000 non-null  object
 47   ACK Flag Count               63000 non-null  object
 48   URG Flag Count               63000 non-null  object
 49   CWE Flag Count               63000 non-null  object
 50   ECE Flag Count               63000 non-null  object
 51   Down/Up Ratio                63000 non-null  object
 52   Average Packet Size          63000 non-null  float64
 53   Avg Fwd Segment Size         63000 non-null  float64
 54   Avg Bwd Segment Size         63000 non-null  float64
 55   Fwd Header Length.1          63000 non-null  object
 56  Fwd Avg Bytes/Bulk            63000 non-null  object
 57   Fwd Avg Packets/Bulk         63000 non-null  object
 58   Fwd Avg Bulk Rate            63000 non-null  object
 59   Bwd Avg Bytes/Bulk           63000 non-null  object
 60   Bwd Avg Packets/Bulk         63000 non-null  object
 61  Bwd Avg Bulk Rate             63000 non-null  object
 62  Subflow Fwd Packets           63000 non-null  object
 63   Subflow Fwd Bytes            63000 non-null  object
 64   Subflow Bwd Packets          63000 non-null  object
 65   Subflow Bwd Bytes            63000 non-null  object
 66  Init_Win_bytes_forward        63000 non-null  object
 67   Init_Win_bytes_backward      63000 non-null  object
 68   act_data_pkt_fwd             63000 non-null  object
 69   min_seg_size_forward         63000 non-null  object
 70  Active Mean                   63000 non-null  float64
 71   Active Std                   63000 non-null  float64
 72   Active Max                   63000 non-null  object
 73   Active Min                   63000 non-null  object
 74  Idle Mean                     63000 non-null  float64
 75   Idle Std                     63000 non-null  float64
 76   Idle Max                     63000 non-null  object
 77   Idle Min                     63000 non-null  object
 78   Label                        63000 non-null  object
dtypes: float64(24), object(55)
memory usage: 38.5+ MB

In [197]:
# Convert to int separated for clarity and cleanliness of code
def convert_to_int(x):
    return int(x)

In [198]:
for column in data.columns[:-1]: #iterate over all columns up to the last one
    if data[column].dtype == object:
        data[column] = data[column].apply(lambda x: convert_to_int(x))

In [166]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 63000 entries, 0 to 63128
Data columns (total 79 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0    Destination Port             63000 non-null  int64
 1    Flow Duration                63000 non-null  int64
 2    Total Fwd Packets            63000 non-null  int64
 3    Total Backward Packets       63000 non-null  int64
 4   Total Length of Fwd Packets   63000 non-null  int64
 5    Total Length of Bwd Packets  63000 non-null  int64
 6    Fwd Packet Length Max        63000 non-null  int64
 7    Fwd Packet Length Min        63000 non-null  int64
 8    Fwd Packet Length Mean       63000 non-null  float64
 9    Fwd Packet Length Std        63000 non-null  float64
 10  Bwd Packet Length Max         63000 non-null  int64
 11   Bwd Packet Length Min        63000 non-null  int64
 12   Bwd Packet Length Mean       63000 non-null  float64
 13   Bwd Packet Length Std        63000 non-null  float64
 14  Flow Bytes/s                  63000 non-null  float64
 15   Flow Packets/s               63000 non-null  float64
 16   Flow IAT Mean                63000 non-null  float64
 17   Flow IAT Std                 63000 non-null  float64
 18   Flow IAT Max                 63000 non-null  int64
 19   Flow IAT Min                 63000 non-null  int64
 20  Fwd IAT Total                 63000 non-null  int64
 21   Fwd IAT Mean                 63000 non-null  float64
 22   Fwd IAT Std                  63000 non-null  float64
 23   Fwd IAT Max                  63000 non-null  int64
 24   Fwd IAT Min                  63000 non-null  int64
 25  Bwd IAT Total                 63000 non-null  int64
 26   Bwd IAT Mean                 63000 non-null  float64
 27   Bwd IAT Std                  63000 non-null  float64
 28   Bwd IAT Max                  63000 non-null  int64
 29   Bwd IAT Min                  63000 non-null  int64
 30  Fwd PSH Flags                 63000 non-null  int64
 31   Bwd PSH Flags                63000 non-null  int64
 32   Fwd URG Flags                63000 non-null  int64
 33   Bwd URG Flags                63000 non-null  int64
 34   Fwd Header Length            63000 non-null  int64
 35   Bwd Header Length            63000 non-null  int64
 36  Fwd Packets/s                 63000 non-null  float64
 37   Bwd Packets/s                63000 non-null  float64
 38   Min Packet Length            63000 non-null  int64
 39   Max Packet Length            63000 non-null  int64
 40   Packet Length Mean           63000 non-null  float64
 41   Packet Length Std            63000 non-null  float64
 42   Packet Length Variance       63000 non-null  float64
 43  FIN Flag Count                63000 non-null  int64
 44   SYN Flag Count               63000 non-null  int64
 45   RST Flag Count               63000 non-null  int64
 46   PSH Flag Count               63000 non-null  int64
 47   ACK Flag Count               63000 non-null  int64
 48   URG Flag Count               63000 non-null  int64
 49   CWE Flag Count               63000 non-null  int64
 50   ECE Flag Count               63000 non-null  int64
 51   Down/Up Ratio                63000 non-null  int64
 52   Average Packet Size          63000 non-null  float64
 53   Avg Fwd Segment Size         63000 non-null  float64
 54   Avg Bwd Segment Size         63000 non-null  float64
 55   Fwd Header Length.1          63000 non-null  int64
 56  Fwd Avg Bytes/Bulk            63000 non-null  int64
 57   Fwd Avg Packets/Bulk         63000 non-null  int64
 58   Fwd Avg Bulk Rate            63000 non-null  int64
 59   Bwd Avg Bytes/Bulk           63000 non-null  int64
 60   Bwd Avg Packets/Bulk         63000 non-null  int64
 61  Bwd Avg Bulk Rate             63000 non-null  int64
 62  Subflow Fwd Packets           63000 non-null  int64
 63   Subflow Fwd Bytes            63000 non-null  int64
 64   Subflow Bwd Packets          63000 non-null  int64
 65   Subflow Bwd Bytes            63000 non-null  int64
 66  Init_Win_bytes_forward        63000 non-null  int64
 67   Init_Win_bytes_backward      63000 non-null  int64
 68   act_data_pkt_fwd             63000 non-null  int64
 69   min_seg_size_forward         63000 non-null  int64
 70  Active Mean                   63000 non-null  float64
 71   Active Std                   63000 non-null  float64
 72   Active Max                   63000 non-null  int64
 73   Active Min                   63000 non-null  int64
 74  Idle Mean                     63000 non-null  float64
 75   Idle Std                     63000 non-null  float64
 76   Idle Max                     63000 non-null  int64
 77   Idle Min                     63000 non-null  int64
 78   Label                        63000 non-null  object
dtypes: float64(24), int64(54), object(1)
memory usage: 38.5+ MB

We will also look at the correlation between the columns to reduce dimensionality.

In [199]:
data.iloc[:, :-1].corr().style.background_gradient(cmap='coolwarm') #iloc method found on stack exchange

According to my research, rows/columns with NaN have 0 variance, meaning all the values are the same and can be eliminated. We also want to reduce columns that have high correlation.

In [200]:
data = data.loc[:, data.nunique() > 1] # Command to drop non-unique values from geeks for geek

In [201]:
data.iloc[:, :-1].corr().style.background_gradient(cmap='coolwarm') #iloc method found on stack exchange

In [202]:
import numpy as np

#Following code found on stack exchange to remove highly correlated columns
corr_matrix = data.iloc[:, :-1].corr().abs() #Build matrix

#Only examine the upper half of the matrix so we don't delete all columns
upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))

# Find features with correlation greater than 0.90
to_drop = [column for column in upper.columns if any(upper[column] > 0.9)]
print(to_drop)
# Apply list of features to drop to matrix
data.drop(to_drop, axis=1, inplace=True)

[' Total Backward Packets', ' Total Length of Bwd Packets', ' Bwd Packet Length Mean', ' Bwd Packet Length Std', ' Flow IAT Max', ' Flow IAT Min', 'Fwd IAT Total', ' Fwd IAT Mean', ' Fwd IAT Max', ' Fwd IAT Min', ' Bwd IAT Std', ' Bwd IAT Max', ' Fwd Header Length', ' Bwd Header Length', 'Fwd Packets/s', ' Max Packet Length', ' Packet Length Mean', ' Packet Length Std', ' Packet Length Variance', ' SYN Flag Count', ' ECE Flag Count', ' Average Packet Size', ' Avg Fwd Segment Size', ' Avg Bwd Segment Size', ' Fwd Header Length.1', 'Subflow Fwd Packets', ' Subflow Fwd Bytes', ' Subflow Bwd Packets', ' Subflow Bwd Bytes', 'Init_Win_bytes_forward', ' act_data_pkt_fwd', ' Active Max', ' Active Min', 'Idle Mean', ' Idle Max', ' Idle Min']

In [203]:
data.iloc[:, :-1].corr().style.background_gradient(cmap='coolwarm') #iloc method found on stack exchange

In [179]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 63000 entries, 0 to 63128
Data columns (total 34 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0    Destination Port            63000 non-null  int64
 1    Flow Duration               63000 non-null  int64
 2    Total Fwd Packets           63000 non-null  int64
 3   Total Length of Fwd Packets  63000 non-null  int64
 4    Fwd Packet Length Max       63000 non-null  int64
 5    Fwd Packet Length Min       63000 non-null  int64
 6    Fwd Packet Length Mean      63000 non-null  float64
 7    Fwd Packet Length Std       63000 non-null  float64
 8   Bwd Packet Length Max        63000 non-null  int64
 9    Bwd Packet Length Min       63000 non-null  int64
 10  Flow Bytes/s                 63000 non-null  float64
 11   Flow Packets/s              63000 non-null  float64
 12   Flow IAT Mean               63000 non-null  float64
 13   Flow IAT Std                63000 non-null  float64
 14   Fwd IAT Std                 63000 non-null  float64
 15  Bwd IAT Total                63000 non-null  int64
 16   Bwd IAT Mean                63000 non-null  float64
 17   Bwd IAT Min                 63000 non-null  int64
 18  Fwd PSH Flags                63000 non-null  int64
 19   Bwd Packets/s               63000 non-null  float64
 20   Min Packet Length           63000 non-null  int64
 21   Packet Length Mean          63000 non-null  float64
 22  FIN Flag Count               63000 non-null  int64
 23   RST Flag Count              63000 non-null  int64
 24   PSH Flag Count              63000 non-null  int64
 25   ACK Flag Count              63000 non-null  int64
 26   URG Flag Count              63000 non-null  int64
 27   Down/Up Ratio               63000 non-null  int64
 28   Init_Win_bytes_backward     63000 non-null  int64
 29   min_seg_size_forward        63000 non-null  int64
 30  Active Mean                  63000 non-null  float64
 31   Active Std                  63000 non-null  float64
 32   Idle Std                    63000 non-null  float64
 33   Label                       63000 non-null  object
dtypes: float64(13), int64(20), object(1)
memory usage: 16.8+ MB

Now we should have a cleaned data set that is properly labeled. We can now load the data to a csv file

In [204]:
# load to a csv file
def loadcsv(data: pd.DataFrame) -> None:
    """This function loads the argument dataframe into a csv file

    Args:
        data (pd.DataFrame): extracted nd transformed dataframe
    """
    data.to_csv('packet_ids.csv', index=False)

In [205]:
loadcsv(data)

We will now split and standardize the data.

In [1]:
! pwd

/content